events {

}

# HTTP全体

http {
	include 	/etc/nginx/mime.types;
	default_type application/octet-stream;

	# TLS 終端: https://nginx.org/en/docs/http/ngx_http_ssl_module.html
	server {
		listen 443 ssl;
		server_name tvaroux.42.fr;
		ssl_certificate /etc/nginx/ssl/tvaroux_server.crt;
		ssl_certificate_key /etc/nginx/ssl/tvaroux_server.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ .*\.(jpg|jpeg|gif|png|css|js|ico|woff)$ {
			expires 42m;
		}

		# FastCGI: https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html
		location ~ \.php$ {
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}
}
